"""removing instrument_id from musica pieces

Revision ID: 9118bfbf1691
Revises: 5c931a25c5c6
Create Date: 2019-12-19 22:31:28.085443

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9118bfbf1691'
down_revision = '5c931a25c5c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('musical_piece_ibfk_2', 'musical_piece', type_='foreignkey')
    op.drop_column('musical_piece', 'instrument_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('musical_piece', sa.Column('instrument_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('musical_piece_ibfk_2', 'musical_piece', 'instrument', ['instrument_id'], ['id'])
    # ### end Alembic commands ###
